---
db: ./data/db.sqlite
schema:
  attributes:
    title:
      name: название
      type: input
    status:
      name: статус
      type: input
      values:
        - устный заказ
        - указание директора
        - доклад менеджера
        - заявка
        - выполнено
        - отправить в архив
    category:
      name: категория
      type: select
      values:
        - категория 1
        - категория 2
        - категория 3
    customer:
      name: заказчик
      type: select
      values:
        - заказчик 1
        - заказчик 2
        - заказчик 3
    type:
      name: вид
      type: multiSelect
      values:
        - водопровод
        - обои
        - штукатурка
    internalCode:
      name: шифр
      type: input
    managerZone:
      name: зона менеджера
      type: multiSelect
      values:
        - отдел 1
        - отдел 2
        - отдел 3