---
db: ./data/db.sqlite
schema:
  attributes:
    title:
      name: название
      type: input
    status:
      name: статус
      type: input
      values:
        - устный заказ
        - указание директора
        - доклад менеджера
        - заявка
        - выполнено
        - отправить в архив
    category:
      name: категория
      type: select
      values:
        - cat1
        - cat2
        - cat3
    customer:
      name: заказчик
      type: select
      values:
        - cust1
        - cust2
        - cust3
    type:
      type: multiSelect
      values:
        - type1
        - type2
        - type3
    internalCode:
      type: input
    managerZone:
      type: multiSelect
      values:
        - zone1
        - zone2
        - zone3