---
db: ./data/db.sqlite
schema:
  attributes:
    status:
      values:
        - устный заказ
        - указание директора
        - доклад менеджера
        - заявка
        - выполнено
        - отправить в архив